PUT http://localhost:3005/api/blogs/62570586831a68439f3724d0 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dnMjQzNDMyIiwiaWQiOiI2MjUyZTAzMDllNGIxOTRmODdkODA1OWIiLCJpYXQiOjE2NDk2MDcxMDMsImV4cCI6MTY0OTYxMDcwM30.GyBZ_i8UDf8yt1fZsX4nyrFyJb5Jwyynu2P4m-FqVEs


{
    "title": "UPDATED BLOG!",
    "author": "UPDATED bloggerGuy",
    "url": "UPDATED http",
    "likes": 5000
}